
# Travis CI build configuration
# Creator: Tyler Vanderhoef

# Specify the OS types to build on
os:
  - linux
  #- osx

osx_image: xcode6.4
  
# The language to use while building
language: cpp

# The script to run when it builds on Travis CI
script: make && make test

# The compiler to target. Here, we use both clang and gcc to see
# if the build works for both systems.
compiler:
  - clang

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - zlib1g-dev
    - llvm

notifications:
  email: 
    on_success: never
    on_failure: never
