
# Travis CI build configuration
# Creator: Tyler Vanderhoef

# Specify the OS types to build on
os:
  #- linux
  - osx

osx_image: xcode6.4
  
# The language to use while building
language: cpp

# The script to run when it builds on Travis CI
script: make && make test

# The compiler to target. Here, we use both clang and gcc to see
# if the build works for both systems.
compiler:
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
    - clang-3.8
    - zlib1g-dev
    - llvm-3.8
    - llvm-3.8-dev

notifications:
  email: 
    on_success: never
    on_failure: never
